version: "3"
services:
  uai_food:
    image: postgres
    container_name: "postgres"
    environment:
      - POSTGRES_DB=uai_food
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432